/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Viewer;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Property.Offer;
import model.Viewer.Viewer;

/**
 *
 * @author Admin
 */
public class ModifyOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModifyOfferJPanel
     */
    JPanel viewerWorkArea;
    Business business;
    Viewer viewer;
    Offer offer;
    public ModifyOfferJPanel(JPanel viewerWorkArea, Business business, Viewer viewer,Offer selectedOffer) {
        initComponents();
        this.viewerWorkArea = viewerWorkArea;
        this.business = business;
        this.viewer = viewer;
        this.offer = selectedOffer;
        txtProperty.setText(this.offer.toString());
        txtListedPrice.setText(String.valueOf(this.offer.getProperty().getRate()));
        txtPreviousOffer.setText (String.valueOf(this.offer.getOfferedRate()));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblProperty = new javax.swing.JLabel();
        txtProperty = new javax.swing.JTextField();
        lblListedPrice = new javax.swing.JLabel();
        txtListedPrice = new javax.swing.JTextField();
        lblPreviousOffer = new javax.swing.JLabel();
        txtPreviousOffer = new javax.swing.JTextField();
        lblNewOffer = new javax.swing.JLabel();
        txtNewOffer = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Modify Offer");

        lblProperty.setText("Property :");

        txtProperty.setEnabled(false);

        lblListedPrice.setText("Listed Price :");

        txtListedPrice.setEnabled(false);

        lblPreviousOffer.setText("Previous Offer :");

        txtPreviousOffer.setEnabled(false);

        lblNewOffer.setText("New Offer :");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNewOffer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPreviousOffer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPreviousOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblListedPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtListedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProperty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(385, 385, 385))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProperty)
                    .addComponent(txtProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListedPrice)
                    .addComponent(txtListedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreviousOffer)
                    .addComponent(txtPreviousOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewOffer)
                    .addComponent(txtNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        // Validate Offered Rate
        String offerRateText = txtNewOffer.getText().trim();
        if (offerRateText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Offered Rate", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }
        // Assuming the offered rate should be a valid double value
        try {
            double offeredRate = Double.parseDouble(offerRateText);
            if (offeredRate < 0) {
                JOptionPane.showMessageDialog(null, "Offered Rate cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Stop further processing
            }
            this.offer.setOfferedRate(offeredRate);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid numeric Offered Rate", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        viewerWorkArea.removeAll();
        OfferStatusJPanel osjp = new OfferStatusJPanel(viewerWorkArea,business,viewer);
        viewerWorkArea.add("OfferStatusJPanel",osjp);
        CardLayout layout = (CardLayout) viewerWorkArea.getLayout();
        layout.next(viewerWorkArea);
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblListedPrice;
    private javax.swing.JLabel lblNewOffer;
    private javax.swing.JLabel lblPreviousOffer;
    private javax.swing.JLabel lblProperty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtListedPrice;
    private javax.swing.JTextField txtNewOffer;
    private javax.swing.JTextField txtPreviousOffer;
    private javax.swing.JTextField txtProperty;
    // End of variables declaration//GEN-END:variables
}
