/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Viewer;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Ecosystem.Business;
import model.Employee.Broker;
import model.Property.Offer;
import model.Property.Property;
import model.Property.PropertyDirectory;
import model.UserAccount.UserAccount;
import model.Viewer.Viewer;

/**
 *
 * @author sakshi
 */
public class OfferStatusJPanel extends javax.swing.JPanel {
        Business business;
        JPanel viewerWorkArea;
        Viewer viewer;


    /**
     * Creates new form OfferStatusJPanel
     */
    public OfferStatusJPanel(JPanel ViewerWorkArea, Business business,Viewer viewer) {
        initComponents();
        this.viewerWorkArea=ViewerWorkArea;
        this.business=business;
        this.viewer=viewer;
        refreshTable();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblstatus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnModifyOffer = new javax.swing.JButton();
        btnDeleteOffer = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tblstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Property Name", "Listed Price", "Offered Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblstatus);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Status Of The Application");

        btnModifyOffer.setText("Modify Offer");
        btnModifyOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyOfferActionPerformed(evt);
            }
        });

        btnDeleteOffer.setText("Delete Offer");
        btnDeleteOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOfferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModifyOffer)
                                .addGap(39, 39, 39)
                                .addComponent(btnDeleteOffer))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyOfferActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblstatus.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "No property selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Offer selectedOffer = (Offer) tblstatus.getValueAt(selectedRow, 0);
        ModifyOfferJPanel modify = new ModifyOfferJPanel(viewerWorkArea,business,viewer,selectedOffer);
        viewerWorkArea.removeAll();
        viewerWorkArea.add(modify);
        CardLayout layout = (CardLayout) viewerWorkArea.getLayout();
        layout.next(viewerWorkArea);
    }//GEN-LAST:event_btnModifyOfferActionPerformed

    private void btnDeleteOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOfferActionPerformed
        // TODO add your handling code here:
        int row = tblstatus.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Offer offer = (Offer)tblstatus.getValueAt(row, 0);
        offer.getProperty().removeOffer(offer);
        this.viewer.getMyOffers().remove(offer);
        
        refreshTable();
    }//GEN-LAST:event_btnDeleteOfferActionPerformed
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) tblstatus.getModel();
        model.setRowCount(0); // Clear existing rows
        for (Offer offer : this.viewer.getMyOffers()) {
            Object[] row = new Object[4];
            row[0] = offer;
            row[1] = offer.getProperty().getRate();
            row[2] = offer.getOfferedRate();
            row[3] = offer.getStatus();
            model.addRow(row);
        }
        tblstatus.setModel(model); // Apply the model to the table
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteOffer;
    private javax.swing.JButton btnModifyOffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstatus;
    // End of variables declaration//GEN-END:variables
}
