/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Viewer;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Viewer.Viewer;
import ui.Viewer.ViewerJPanel;

/**
 *
 * @author sakshi
 */
public class ViewerJPanel extends javax.swing.JPanel {
    private JPanel mainWorkArea;
    private Viewer viewer;
    private Business business;

    /**
     * Creates new form ViewerJPanel
     */
    public ViewerJPanel(JPanel mainWorkArea, Viewer viewer, Business business) {
        initComponents();
        this.mainWorkArea=mainWorkArea;
        this.viewer=viewer;
        this.business=business;
        ViewerWorkArea.setLayout(new CardLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        ViewerMenu = new javax.swing.JPanel();
        btnViewProp = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        ViewerWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        ViewerMenu.setBackground(new java.awt.Color(204, 255, 255));

        btnViewProp.setText("View All Properties");
        btnViewProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPropActionPerformed(evt);
            }
        });

        btnStatus.setText("Offer Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewerMenuLayout = new javax.swing.GroupLayout(ViewerMenu);
        ViewerMenu.setLayout(ViewerMenuLayout);
        ViewerMenuLayout.setHorizontalGroup(
            ViewerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewerMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnViewProp)
                .addGap(122, 122, 122)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        ViewerMenuLayout.setVerticalGroup(
            ViewerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewerMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ViewerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(ViewerMenu);

        ViewerWorkArea.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout ViewerWorkAreaLayout = new javax.swing.GroupLayout(ViewerWorkArea);
        ViewerWorkArea.setLayout(ViewerWorkAreaLayout);
        ViewerWorkAreaLayout.setHorizontalGroup(
            ViewerWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        ViewerWorkAreaLayout.setVerticalGroup(
            ViewerWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(ViewerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPropActionPerformed
        // TODO add your handling code here:
        
        ViewPropertiesJPanel vpjp = new ViewPropertiesJPanel(ViewerWorkArea,business,viewer);
        ViewerWorkArea.removeAll();
        ViewerWorkArea.add(vpjp);
        CardLayout layout = (CardLayout) ViewerWorkArea.getLayout();
        layout.next(ViewerWorkArea);
    }//GEN-LAST:event_btnViewPropActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        
        mainWorkArea.remove(this); 
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
        ViewerWorkArea.removeAll();
        OfferStatusJPanel osjp = new OfferStatusJPanel(ViewerWorkArea,business,viewer);
        ViewerWorkArea.add("OfferStatusJPanel",osjp);
        CardLayout layout = (CardLayout) ViewerWorkArea.getLayout();
        layout.next(ViewerWorkArea);
    }//GEN-LAST:event_btnStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewerMenu;
    private javax.swing.JPanel ViewerWorkArea;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnViewProp;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
            }
