/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Ecosystem.mailer.EmailUtil;
import model.Ecosystem.mailer.MessagesClass;
import model.Enterprise.Enterprise;
import model.Enterprise.EnterpriseDirectory;
import model.Enterprise.ViewerEnterprise;
import model.Organisation.Organisation;
import model.Organisation.ViewerOrganisation;
import model.UserAccount.UserAccountDirectory;
import model.Viewer.Viewer;
import model.Viewer.ViewerDirectory;

/**
 *
 * @author Admin
 */
public class AddNewViewersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewViewersJPanel
     */
    JPanel sysAdminWorkarea;
    Business business;
    public AddNewViewersJPanel(JPanel sysAdminWorkarea, Business business) {
        initComponents();
        this.sysAdminWorkarea = sysAdminWorkarea;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        pwdViewer = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 204, 204));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Viewer");

        jLabel3.setText("Email :");

        jLabel4.setText("Password :");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        pwdViewer.setText("Password123@");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(pwdViewer))
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(404, 404, 404))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwdViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.remove(this);
        CardLayout layout = (CardLayout)sysAdminWorkarea.getLayout();
        layout.previous(sysAdminWorkarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // Validate Name
        String username = txtName.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Viewer Name", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        // Validate Password
        String password = new String(pwdViewer.getPassword());
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Password", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        EnterpriseDirectory ed = this.business.getEnterpriseDirectory();
        UserAccountDirectory userAccountDirectory = this.business.getBusinessUserDirectory();
        for (Enterprise enterprise : ed.getEnterpriseList()) {
            if (enterprise instanceof ViewerEnterprise re) {
                for (Organisation org : re.getOrganisationDirectory().getOrganisationList()) {
                    if (org instanceof ViewerOrganisation viewerOrg) {
                        ViewerDirectory viewerDirectory = viewerOrg.getViewerDirectory();

                        // Create and add new viewer
                        Viewer viewer = new Viewer(username, password);
                        viewerDirectory.addNewViewer(viewer);
                        userAccountDirectory.addNewUserAccount(viewer);
                    }
                }
            }
        }
        EmailUtil emailUtil = new EmailUtil();
        MessagesClass messagesClass = new MessagesClass();
        emailUtil.sendEmailAlert(username,messagesClass.getSubjectAccountCreation(),messagesClass.getBrokerAccountCreation());
        sysAdminWorkarea.removeAll();
        SysAdminViewerJPanel viewers = new SysAdminViewerJPanel(sysAdminWorkarea,business);
        viewers.populateTable();
        sysAdminWorkarea.add("sysAdminViewerJPanel",viewers);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwdViewer;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
