/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Ecosystem.mailer.EmailUtil;
import model.Ecosystem.mailer.MessagesClass;
import model.Employee.Broker;
import model.Employee.EmployeeDirectory;
import model.Enterprise.Enterprise;
import model.Enterprise.EnterpriseDirectory;
import model.Enterprise.RealEstateAgencyEnterprise;
import model.Organisation.Organisation;
import model.Organisation.PropertyManagementOrganisation;
import model.UserAccount.UserAccount;
import model.UserAccount.UserAccountDirectory;

/**
 *
 * @author Admin
 */
public class AddNewBrokerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewBrokerJPanel
     */
    JPanel sysAdminWorkarea;
    Business business;
    public AddNewBrokerJPanel(JPanel sysAdminWorkarea, Business business) {
        initComponents();
        this.sysAdminWorkarea = sysAdminWorkarea;
        this.business = business;
        populateAgencies();
    }
    private void populateAgencies(){
        cmbAgency.removeAllItems();
        EnterpriseDirectory ed=this.business.getEnterpriseDirectory();
        for(Enterprise enterprise:ed.getEnterpriseList()) {
            if(enterprise instanceof RealEstateAgencyEnterprise realEstateEnterprise){
                cmbAgency.addItem(realEstateEnterprise.getName());  
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAgency = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        pwdBroker = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 204, 204));

        cmbAgency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgencyActionPerformed(evt);
            }
        });

        jLabel1.setText("Real Estate Agency : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Broker");

        jLabel3.setText("Broker Email :");

        jLabel4.setText("Password :");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setText("ID : ");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pwdBroker.setText("Password123@");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(421, 421, 421))))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbAgency, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(pwdBroker))
                .addGap(0, 309, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwdBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       // Validate Name
        String username = txtName.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Broker Name", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        // Validate Password
        String password = new String(pwdBroker.getPassword());
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Password", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        // Validate ID
        String id = txtId.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter ID", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        EnterpriseDirectory ed = this.business.getEnterpriseDirectory();
        UserAccountDirectory userAccountDirectory = this.business.getBusinessUserDirectory();
        for (Enterprise enterprise : ed.getEnterpriseList()) {
            if (enterprise instanceof RealEstateAgencyEnterprise re && re.getName().equals(cmbAgency.getSelectedItem())) {
                for (Organisation org : re.getOrganisationDirectory().getOrganisationList()) {
                    if (org instanceof PropertyManagementOrganisation pmo) {
                        EmployeeDirectory employeeDirectory = pmo.getEmployeeDirectory();
                        // Create and add new broker employee
                        Broker broker = new Broker(username, password, id);
                        employeeDirectory.addNewEmployee(broker);
                        userAccountDirectory.addNewUserAccount(broker);
                    }
                }
            }
        }
        EmailUtil emailUtil = new EmailUtil();
        MessagesClass messagesClass = new MessagesClass();
        emailUtil.sendEmailAlert(username,messagesClass.getSubjectAccountCreation(),messagesClass.getBrokerAccountCreation());
        // Remove all components from sysAdminWorkarea and add SysAdminBrokersJPanel
        sysAdminWorkarea.removeAll();
        SysAdminBrokersJPanel brokers = new SysAdminBrokersJPanel(sysAdminWorkarea, business);
        brokers.populateTable();
        sysAdminWorkarea.add("sysAdminBrokersJPanel", brokers);

        // Switch to the new panel
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.remove(this);
        CardLayout layout = (CardLayout)sysAdminWorkarea.getLayout();
        layout.previous(sysAdminWorkarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAgencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbAgency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwdBroker;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
