/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.SystemAdmin.SystemAdmin;


/**
 *
 * @author sakshi
 */
public class SysAdminJPanel extends javax.swing.JPanel {
    
    private JPanel mainWorkArea;
    private SystemAdmin sysAdmin;
    private Business business;


    /**
     * Creates new form SysAdminJPanel
     */
    public SysAdminJPanel(JPanel mainWorkArea, SystemAdmin sysAdmin, Business business) {
        initComponents();
        this.mainWorkArea=mainWorkArea;
        this.sysAdmin=sysAdmin;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sysAdminMenu = new javax.swing.JPanel();
        btnProperties = new javax.swing.JButton();
        btnAgencies = new javax.swing.JButton();
        btnBrokers = new javax.swing.JButton();
        btnViewers = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        sysAdminWorkarea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        sysAdminMenu.setBackground(new java.awt.Color(204, 255, 255));

        btnProperties.setText("Properties");
        btnProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropertiesActionPerformed(evt);
            }
        });

        btnAgencies.setText("Real Estate Agencies");
        btnAgencies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenciesActionPerformed(evt);
            }
        });

        btnBrokers.setText("Brokers");
        btnBrokers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrokersActionPerformed(evt);
            }
        });

        btnViewers.setText("Viewers");
        btnViewers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewersActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysAdminMenuLayout = new javax.swing.GroupLayout(sysAdminMenu);
        sysAdminMenu.setLayout(sysAdminMenuLayout);
        sysAdminMenuLayout.setHorizontalGroup(
            sysAdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnProperties)
                .addGap(28, 28, 28)
                .addComponent(btnAgencies)
                .addGap(31, 31, 31)
                .addComponent(btnBrokers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnViewers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        sysAdminMenuLayout.setVerticalGroup(
            sysAdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(sysAdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgencies, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrokers, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewers, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(sysAdminMenu);

        sysAdminWorkarea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(sysAdminWorkarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropertiesActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.removeAll();
        SysAdminPropertiesJPanel properties = new SysAdminPropertiesJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("SysAdminPropertiesJPanel",properties);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnPropertiesActionPerformed

    private void btnAgenciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenciesActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.removeAll();
        SysAdminAgenciesJPanel agencies = new SysAdminAgenciesJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("sysAdminAgenciesJPanel",agencies);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnAgenciesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this); 
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBrokersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrokersActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.removeAll();
        SysAdminBrokersJPanel brokers = new SysAdminBrokersJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("sysAdminBrokersJPanel",brokers);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnBrokersActionPerformed

    private void btnViewersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewersActionPerformed
        // TODO add your handling code here:
        sysAdminWorkarea.removeAll();
        SysAdminViewerJPanel brokers = new SysAdminViewerJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("sysAdminViewerJPanel",brokers);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnViewersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgencies;
    private javax.swing.JButton btnBrokers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProperties;
    private javax.swing.JButton btnViewers;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel sysAdminMenu;
    private javax.swing.JPanel sysAdminWorkarea;
    // End of variables declaration//GEN-END:variables
}
