/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Ecosystem.Business;
import model.Employee.Broker;
import model.Enterprise.Enterprise;
import model.Enterprise.EnterpriseDirectory;
import model.Enterprise.RealEstateAgencyEnterprise;
import model.Enterprise.ViewerEnterprise;
import model.Organisation.Organisation;
import model.Organisation.PropertyManagementOrganisation;
import model.Organisation.ViewerOrganisation;
import model.UserAccount.UserAccount;
import model.Viewer.Viewer;

/**
 *
 * @author Admin
 */
public class SysAdminViewerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminViewerJPanel
     */
    JPanel sysAdminWorkarea;
    Business business;    
    public SysAdminViewerJPanel(JPanel sysAdminWorkarea, Business business) {
        initComponents();
        this.sysAdminWorkarea = sysAdminWorkarea;
        this.business = business;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblViewers.getModel();
        model.setRowCount(0);
        EnterpriseDirectory ed=this.business.getEnterpriseDirectory();
        for(Enterprise enterprise:ed.getEnterpriseList()) {
            if(enterprise instanceof ViewerEnterprise viewerEnterprise){
                for(Organisation org:viewerEnterprise.getOrganisationDirectory().getOrganisationList()){
                    ViewerOrganisation viewerOrg = (ViewerOrganisation) org;
                    for(Viewer viewer:viewerOrg.getViewerDirectory().getViewerList()){
                        Object row[] = new Object[2];
                        row[0] = viewer;
                        row[1] = viewer.getMyOffers().size();
                        model.addRow(row);
                    }
                }
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewers = new javax.swing.JTable();
        btnAddNewViewer = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        tblViewers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Viewer", "Offers made"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewers);

        btnAddNewViewer.setText("Add New Viewer");
        btnAddNewViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewViewerActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Offers Made");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewViewerActionPerformed
        // TODO add your handling code here:
        AddNewViewersJPanel agency = new AddNewViewersJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("AddNewViewersJPanel",agency);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnAddNewViewerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblViewers.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Viewer v = (Viewer) tblViewers.getValueAt(row, 0);
        ArrayList<UserAccount> list = business.getBusinessUserDirectory().getUserAccountList();
        Iterator<UserAccount> iterator = list.iterator();
        while (iterator.hasNext()) {
            UserAccount user = iterator.next();
            if (user.getUsername().equals(v.getUsername())) {
                iterator.remove(); // Remove the element using the iterator
            }
        }
        for (Enterprise ent : business.getEnterpriseDirectory().getEnterpriseList()) {
            if (ent.getType().equals("Viewer")) {
                for (Organisation org : ent.getOrganisationDirectory().getOrganisationList()) {
                    if (org instanceof ViewerOrganisation viewer) {
                        viewer.getViewerDirectory().getViewerList().remove(v);
                    }
                }
            }
        }
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewViewer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewers;
    // End of variables declaration//GEN-END:variables
}
