/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Ecosystem.Business;
import model.Enterprise.Enterprise;
import model.Enterprise.EnterpriseDirectory;
import model.Enterprise.RealEstateAgencyEnterprise;

/**
 *
 * @author Admin
 */
public class SysAdminAgenciesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminAgenciesJPanel
     */
    JPanel sysAdminWorkarea;
    Business business;
    public SysAdminAgenciesJPanel(JPanel sysAdminWorkarea, Business business) {
        initComponents();
        this.sysAdminWorkarea = sysAdminWorkarea;
        this.business = business;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblAgencies.getModel();
        model.setRowCount(0);
        EnterpriseDirectory ed=this.business.getEnterpriseDirectory();
        for(Enterprise enterprise:ed.getEnterpriseList()) {
            if(enterprise instanceof RealEstateAgencyEnterprise realEstateEnterprise){
                Object row[] = new Object[2];
                row[0] = realEstateEnterprise;
                row[1] = realEstateEnterprise.getAllProperties().size();
                model.addRow(row);
            } 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgencies = new javax.swing.JTable();
        btnAddNewAgency = new javax.swing.JButton();
        btnEditAgency = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        tblAgencies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Real Estate Agency", "Number of Properties"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAgencies);

        btnAddNewAgency.setText("Add New Agency");
        btnAddNewAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewAgencyActionPerformed(evt);
            }
        });

        btnEditAgency.setText("Edit Agency Details");
        btnEditAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAgencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnEditAgency)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewAgencyActionPerformed
        // TODO add your handling code here:
        AddNewAgencyJPanel agency = new AddNewAgencyJPanel(sysAdminWorkarea,business);
        sysAdminWorkarea.add("AddNewAgencyJPanel",agency);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnAddNewAgencyActionPerformed

    private void btnEditAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAgencyActionPerformed
        // TODO add your handling code here:
        int row = tblAgencies.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RealEstateAgencyEnterprise enterprise = (RealEstateAgencyEnterprise) tblAgencies.getValueAt(row, 0);
        UpdateAgencyJPanel agency = new UpdateAgencyJPanel(sysAdminWorkarea,business,enterprise);
        sysAdminWorkarea.add("UpdateAgencyJPanel",agency);
        CardLayout layout = (CardLayout) sysAdminWorkarea.getLayout();
        layout.next(sysAdminWorkarea);
    }//GEN-LAST:event_btnEditAgencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewAgency;
    private javax.swing.JButton btnEditAgency;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgencies;
    // End of variables declaration//GEN-END:variables
}
