/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RealEstateAgency.Broker;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Employee.Broker;

/**
 *
 * @author sakshi
 */
public class BrokerJPanel extends javax.swing.JPanel {
    private JPanel mainWorkArea;
    private Broker broker;
    private Business business;


    /**
     * Creates new form BrokerJPanel
     */
    public BrokerJPanel(JPanel mainWorkArea, Broker broker, Business business) {
        initComponents();
        this.mainWorkArea=mainWorkArea;
        this.broker=broker;
        this.business=business;
        if (broker != null) lblWelcome.setText("Welcome "+broker.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        brokerMenu = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnAddNewProperty = new javax.swing.JButton();
        btnViewCustomerOffers = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        brokerWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        brokerMenu.setBackground(new java.awt.Color(204, 255, 255));

        lblWelcome.setText("<WelcomeMsg>");

        btnView.setText("View Properties");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAddNewProperty.setText("Add New Property");
        btnAddNewProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPropertyActionPerformed(evt);
            }
        });

        btnViewCustomerOffers.setText("View Customer Offers");
        btnViewCustomerOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerOffersActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout brokerMenuLayout = new javax.swing.GroupLayout(brokerMenu);
        brokerMenu.setLayout(brokerMenuLayout);
        brokerMenuLayout.setHorizontalGroup(
            brokerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brokerMenuLayout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(lblWelcome)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(brokerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView)
                .addGap(111, 111, 111)
                .addComponent(btnAddNewProperty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnViewCustomerOffers)
                .addGap(84, 84, 84)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        brokerMenuLayout.setVerticalGroup(
            brokerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brokerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brokerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnAddNewProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCustomerOffers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jSplitPane1.setTopComponent(brokerMenu);

        brokerWorkArea.setBackground(new java.awt.Color(255, 255, 204));
        brokerWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(brokerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPropertyActionPerformed
        // TODO add your handling code here:
        brokerWorkArea.removeAll();
        AddNewPropertyJPanel addNewProperty = new AddNewPropertyJPanel(brokerWorkArea,broker, business);
        brokerWorkArea.add("AddNewPropertyJPanel",addNewProperty);
        CardLayout layout = (CardLayout) brokerWorkArea.getLayout();
        layout.next(brokerWorkArea);
    }//GEN-LAST:event_btnAddNewPropertyActionPerformed

    private void btnViewCustomerOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerOffersActionPerformed
        // TODO add your handling code here:
        brokerWorkArea.removeAll();
        ViewCustomerOfferJPanel viewCustomerOffer = new ViewCustomerOfferJPanel(brokerWorkArea,broker);
        brokerWorkArea.add("ViewCustomerOfferJPanel",viewCustomerOffer);
        CardLayout layout = (CardLayout) brokerWorkArea.getLayout();
        layout.next(brokerWorkArea);
    }//GEN-LAST:event_btnViewCustomerOffersActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        brokerWorkArea.removeAll();
        ViewPropertiesJPanel brokerProperties = new ViewPropertiesJPanel(brokerWorkArea,broker);
        brokerWorkArea.add("ViewPropertiesJPanel",brokerProperties);
        CardLayout layout = (CardLayout) brokerWorkArea.getLayout();
        layout.next(brokerWorkArea);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this); 
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brokerMenu;
    private javax.swing.JPanel brokerWorkArea;
    private javax.swing.JButton btnAddNewProperty;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewCustomerOffers;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
