/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RealEstateAgency.Supervisor;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Ecosystem.Business;
import model.Employee.Broker;
import model.Employee.Supervisor;
import model.Enterprise.Enterprise;
import model.Organisation.Organisation;



/**
 *
 * @author sakshi
 */
public class SupervisorJPanel extends javax.swing.JPanel {
    private JPanel mainWorkArea;
    private Supervisor supervisor;
    private Business business;


    /**
     * Creates new form SupervisorJPanel
     */
    public SupervisorJPanel(JPanel mainWorkArea, Supervisor supervisor, Business business) {
        initComponents();
        this.mainWorkArea=mainWorkArea;
        this.supervisor =supervisor;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        supervisorMenu = new javax.swing.JPanel();
        btnViewPropertiesAgency = new javax.swing.JButton();
        btnViewOffersAgency = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        supervisorWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        supervisorMenu.setBackground(new java.awt.Color(204, 255, 255));

        btnViewPropertiesAgency.setText("View Properties");
        btnViewPropertiesAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPropertiesAgencyActionPerformed(evt);
            }
        });

        btnViewOffersAgency.setText("View Offers");
        btnViewOffersAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOffersAgencyActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout supervisorMenuLayout = new javax.swing.GroupLayout(supervisorMenu);
        supervisorMenu.setLayout(supervisorMenuLayout);
        supervisorMenuLayout.setHorizontalGroup(
            supervisorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorMenuLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(btnViewPropertiesAgency)
                .addGap(66, 66, 66)
                .addComponent(btnViewOffersAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        supervisorMenuLayout.setVerticalGroup(
            supervisorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supervisorMenuLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(supervisorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supervisorMenuLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(supervisorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewOffersAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewPropertiesAgency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jSplitPane1.setTopComponent(supervisorMenu);

        supervisorWorkArea.setBackground(new java.awt.Color(204, 255, 204));
        supervisorWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(supervisorWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPropertiesAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPropertiesAgencyActionPerformed
        // TODO add your handling code here:
        supervisorWorkArea.removeAll();
        ViewPropertiesAgencyJPanel agencyProperties = new ViewPropertiesAgencyJPanel(supervisorWorkArea,supervisor,business);
        supervisorWorkArea.add("ViewPropertiesAgencyJPanel",agencyProperties);
        CardLayout layout = (CardLayout) supervisorWorkArea.getLayout();
        layout.next(supervisorWorkArea);
    }//GEN-LAST:event_btnViewPropertiesAgencyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this); 
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewOffersAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOffersAgencyActionPerformed
        // TODO add your handling code here:
        supervisorWorkArea.removeAll();
        ViewOffersAgencyJPanel agencyOffers = new ViewOffersAgencyJPanel(supervisorWorkArea,supervisor,business);
        supervisorWorkArea.add("supervisorWorkAreaViewBrokersAgencyJPanel",agencyOffers);
        CardLayout layout = (CardLayout) supervisorWorkArea.getLayout();
        layout.next(supervisorWorkArea);
    }//GEN-LAST:event_btnViewOffersAgencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewOffersAgency;
    private javax.swing.JButton btnViewPropertiesAgency;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel supervisorMenu;
    private javax.swing.JPanel supervisorWorkArea;
    // End of variables declaration//GEN-END:variables
}
